#
# Nvidia TensorFlow 1.15 & Python3 base image for JetPack 4.2
#
# sudo docker run -it --rm --runtime nvidia --network host
#
FROM nvcr.io/nvidia/l4t-tensorflow:r32.5.0-tf2.3-py3

RUN apt-get update && apt-get install -y lsb-release && apt-get clean all

# Need sudo if inside the container as appuser
RUN apt-get install -y sudo

# Install Python Libraries - no virtual env as this is canned environment anyway.

RUN useradd appuser -m && usermod --shell /bin/bash appuser && usermod -aG sudo appuser && \
    echo "appuser\nappuser" | passwd appuser && \
    echo "root\nroot" | passwd root

# Check all dependencies are in place for Jupyter
RUN sudo apt-get -y install build-essential libssl-dev libffi-dev python-dev

# Jupyter install.
RUN pip3 install jupyter

# Need to pull down experimental source trees.
RUN apt-get install -y git

RUN echo 'cd ~' >> /home/appuser/.bashrc

RUN chown -R appuser:appuser /home/appuser

USER appuser
